### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by vishnu88alpha** [Krishna12432002/Project1#1]
Login Page has a bug where it fails to navigate in the first attempt entering credentials . But on every second attempt it is logging issue. Look over the issue

**Comment by vishnu88alpha** [comment]
I am working on Login screen. Trying to recreate the bug and will find an apt solution for the bug. On first review it seems to be a problem in the code flow of execution. Will be resolved ASAP. Complete explanation will be documented.

**Comment by vishnu88alpha** [comment]
Login Screen bug fixed. Rewrote the whole code for proper functioning, 
Created three stack navigation components and splitted the screen imports into three categories.

**Comment by vishnu88alpha** [comment]
done

**Comment by Krishna12432002** [comment]
ok
